//
//  UserPresenter.swift
//  wallet
//
//  Created by Pietro Basso on 20/02/2019.
//  Copyright (c) 2019 Pietro Basso. All rights reserved.
//
//  This file was generated by the Lisca Xcode Templates so
//  you can apply lisca architecture to your iOS projects
//

import UIKit
import RxSwift
import RxCocoa

protocol UserPresenterInput {
    var state: Observable<UserState> { get }
}

class UserPresenter: UserViewControllerInput {
    
    // MARK: UserViewControllerInput
    let title: Driver<String>
    let dataSource: Driver<[Section<Action.Descriptor>]>
    
    init(input: UserPresenterInput) {
        title = input.state
            .map { state -> String in "You" }
            .asDriver(onErrorJustReturn: "")
        dataSource = input.state
            .map { $0.actions }
            .distinctUntilChanged()
            .map { actions in
                return [Section<Action.Descriptor>(title: "Actions",
                                                   dataSource: actions.map { $0.descriptor })]
            }
            .asDriver(onErrorJustReturn: [])
    }
}
