//
//  UserCoordinator.swift
//  wallet
//
//  Created by Pietro Basso on 20/02/2019.
//  Copyright (c) 2019 Pietro Basso. All rights reserved.
//
//  This file was generated by the Lisca Xcode Templates so
//  you can apply lisca architecture to your iOS projects
//

import UIKit

class UserCoordinator: NavigationCoordinator {
    var childrenCoordinators: [Coordinator] = []
    let viewController: UIViewController
    let navigationController: UINavigationController

    weak var delegate: CoordinatorDelegate?
    private let navigationControllerDelegate = CustomNavigationControllerDelegate { (navigationController, viewController, animated) in
        navigationController.navigationBar.prefersLargeTitles = true
    }
    
    init(dependencies: AppDependencies, navigationController: UINavigationController? = nil) {
        let interactor = UserInteractor(dependencies: dependencies)
        let presenter = UserPresenter(input: interactor)
        let viewController = UserViewController(input: presenter, output: interactor)
        if let navigationController = navigationController {
            self.viewController = viewController
            self.navigationController = navigationController
        } else {
            self.navigationController = UINavigationController(rootViewController: viewController)
            self.viewController = self.navigationController
        }
        interactor.delegate = self
        self.navigationController.delegate = navigationControllerDelegate
    }
    
    func start() { }

    private func pushChildScene() {
//        let coordinator = ChildCoordinator(dependencies: dependencies, navigationController: navigationController)
//        coordinator.delegate = self
//        coordinator.start()
//        push(child: coordinator)
    }    
}

// MARK: - Extension: UserInteractorDelegate
extension UserCoordinator: UserInteractorDelegate {
    func open(url: URL) {
        UIApplication.shared.open(url)
    }
}
