//
//  CardsPresenter.swift
//  wallet
//
//  Created by Pietro Basso on 14/02/2019.
//  Copyright (c) 2019 Pietro Basso. All rights reserved.
//
//  This file was generated by the Lisca Xcode Templates so
//  you can apply lisca architecture to your iOS projects
//

import UIKit
import RxSwift
import RxCocoa

protocol CardsPresenterInput {
    var state: Observable<CardsState> { get }
}

class CardsPresenter: CardsViewControllerInput {
    
    // MARK: CardsViewControllerInput
    let title: Driver<String>
    let dataSource: Driver<[CardCellViewModel]>
    
    init(input: CardsPresenterInput) {
        title = input.state
            .map { state -> String in "Cards" }
            .asDriver(onErrorJustReturn: "")
        dataSource = input.state
            .map { state in
                var dataSource = Set<CardCellViewModel>()
                for _ in 0...6 { dataSource.insert(CardCellViewModel.random) }
                return Array(dataSource)
            }
            .asDriver(onErrorJustReturn: [])
    }
}
