//
//  CardsInteractor.swift
//  wallet
//
//  Created by Pietro Basso on 14/02/2019.
//  Copyright (c) 2019 Pietro Basso. All rights reserved.
//
//  This file was generated by the Lisca Xcode Templates so
//  you can apply lisca architecture to your iOS projects
//

import UIKit
import RxSwift
import RxCocoa

protocol CardsInteractorDelegate: class {
    func addCard()
}

struct CardsState {
    
}

class CardsInteractor: CardsViewControllerOutput, CardsPresenterInput, RxStateful {
    
    typealias Action = CardsAction
    typealias State = CardsState
    typealias Dependencies = UserDefaultsServiceProvider
    
    enum Mutation {
        
    }
    
    let initialState = CardsState()
    let dependencies: Dependencies
    
    weak var delegate: CardsInteractorDelegate?
    
    init(dependencies: Dependencies) {
        self.dependencies = dependencies
    }
    
    func mutate(action: Action) -> Observable<Mutation> {
        switch action {
        case .viewLoaded:
            return .empty()
        case .addButtonTapped:
            delegate?.addCard()
            return .empty()
        }
    }
}
