//
//  CardCoordinator.swift
//  wallet
//
//  Created by Pietro Basso on 14/02/2019.
//  Copyright (c) 2019 Pietro Basso. All rights reserved.
//
//  This file was generated by the Lisca Xcode Templates so
//  you can apply lisca architecture to your iOS projects
//

import UIKit

protocol CardCoordinatorDelegate: AnyObject {
    func dismissCard(coordinator: Coordinator)
}

class CardCoordinator: Coordinator {
    var childrenCoordinators: [Coordinator] = []
    let viewController: UIViewController
    
    weak var delegate: CardCoordinatorDelegate?
    
    init(dependencies: AppDependencies, snapshotImage: UIImage?) {
        let interactor = CardInteractor(dependencies: dependencies, snapshotImage: snapshotImage)
        let presenter = CardPresenter(input: interactor)
        viewController = CardViewController(input: presenter, output: interactor)
        interactor.delegate = self
    }
    
    func start() { }
}

// MARK: - Extension: CardInteractorDelegate
extension CardCoordinator: CardInteractorDelegate {
    func dismissAction() {
        delegate?.dismissCard(coordinator: self)
    }
}
