//
//  CardInteractor.swift
//  wallet
//
//  Created by Pietro Basso on 14/02/2019.
//  Copyright (c) 2019 Pietro Basso. All rights reserved.
//
//  This file was generated by the Lisca Xcode Templates so
//  you can apply lisca architecture to your iOS projects
//

import UIKit
import RxSwift
import RxCocoa

protocol CardInteractorDelegate: class {
    func dismissAction()
}

struct CardState {
    let card: Card
    let snapshotImage: UIImage?
    var presenting: Bool
}

class CardInteractor: CardViewControllerOutput, CardPresenterInput, RxStateful {
    
    typealias Action = CardAction
    typealias State = CardState
    typealias Dependencies = UserDefaultsServiceProvider
    
    enum Mutation {
        case animateCard(Bool)
    }
    
    let initialState: CardState
    let dependencies: Dependencies
    
    weak var delegate: CardInteractorDelegate?
    
    init(dependencies: Dependencies, card: Card,  snapshotImage: UIImage?) {
        self.dependencies = dependencies
        initialState = CardState(card: card, snapshotImage: snapshotImage, presenting: false)
    }
    
    func mutate(action: Action) -> Observable<Mutation> {
        switch action {
        case .viewLoaded:
            return .empty()
        case .viewAppeared:
            return .just(.animateCard(true))
        case .presentingCompleted:
            delegate?.dismissAction()
            return .empty()
        case .dismissButtonTapped:
            return .just(.animateCard(false))
        }
    }
    
    func reduce(state: State, mutation: Mutation) -> State {
        var copy = state
        switch mutation {
        case .animateCard(let presenting):
            copy.presenting = presenting
        }
        return copy
    }
}
