//
//  CardsManager.swift
//  wallet
//
//  Created by Pietro Basso on 15/02/2019.
//  Copyright (c) 2019 Pietro Basso. All rights reserved.
//
//  This file was generated by the Lisca Xcode Templates so
//  you can apply lisca architecture to your iOS projects
//

import RxSwift
import RxCocoa

protocol CardsManagerProvider {
    var cardsManager: CardsManager { get }
}

protocol CardsManager {
    var cards: Observable<[Card]> { get }
}

class MockedCardsManager: CardsManager {
    let cards: Observable<[Card]>
    private let _cards = PublishSubject<[Card]>()
    
    init(cardsCount: Int) {
        cards = _cards
            .asObservable()
            .distinctUntilChanged()
            .share(replay: 1, scope: .forever)
        cards.subscribe()
        var mockedCards = Set<Card>()
        for _ in 0..<cardsCount { mockedCards.insert(Card.random) }
        _cards.onNext(Array(mockedCards))
    }
}
