//
//  HomeTabBarController.swift
//  wallet
//
//  Created by Pietro Basso on 14/02/2019.
//  Copyright (c) 2019 Pietro Basso. All rights reserved.
//
//  This file was generated by the Lisca Xcode Templates so
//  you can apply lisca architecture to your iOS projects
//

import UIKit

protocol HomeTabBarControllerDelegate: class {
    func dismissAction()
}

class HomeTabBarController: UITabBarController {
    weak var customDelegate: HomeTabBarControllerDelegate?
    
    override func viewDidDisappear(_ animated: Bool) {
        super.viewDidDisappear(animated)
        if isMovingFromParent {
            customDelegate?.dismissAction()
        }
    }
}
