//
//  OnboardingCoordinator.swift
//  wallet
//
//  Created by Pietro Basso on 14/02/2019.
//  Copyright (c) 2019 Pietro Basso. All rights reserved.
//
//  This file was generated by the Lisca Xcode Templates so
//  you can apply lisca architecture to your iOS projects
//

import UIKit

class OnboardingCoordinator: Coordinator {
    var childrenCoordinators: [Coordinator] = []
    let viewController: UIViewController
    
    weak var delegate: CoordinatorDelegate?
    
    init(dependencies: AppDependencies) {
        let interactor = OnboardingInteractor(dependencies: dependencies)
        let presenter = OnboardingPresenter(input: interactor)
        viewController = OnboardingViewController(input: presenter, output: interactor)
        interactor.delegate = self
    }
    
    func start() { }
}

// MARK: - Extension: OnboardingInteractorDelegate
extension OnboardingCoordinator: OnboardingInteractorDelegate {
    func dismissAction() {
        delegate?.dismiss(coordinator: self)
    }
}
